## to run on 8H200
batch_size = 512
micro_batch_size = 8
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "moonshotai/Moonlight-16B-A3B-Instruct"
trust_remote_code = true

[monitor.wandb]

[environment]
id = "hendrycks-math"

[monitor.wandb.log_extras]
interval = 10

[eval]
interval = 50
environment_ids = ["math500", "aime2024", "aime2025"]
rollouts_per_example = [1, 16, 16]
