max_steps = 500
batch_size = 1024
micro_batch_size = 1
seq_len = 4096
rollouts_per_prompt = 32
mask_truncated_completions = true

[model]
name = "willcb/Qwen3-14B"

[monitor.wandb]

[environment]
id = "wordle"

[environment.args]

[sampling]
max_tokens = 1024

[monitor.wandb.log_samples]
interval = 10

[ckpt]