max_steps = 500
batch_size = 1024
micro_batch_size = 1
seq_len = 4096
rollouts_per_prompt = 16
mask_truncated_completions = false

[model]
name = "willcb/Qwen3-1.7B-Wordle"

[monitor.wandb]

[environment]
id = "wordle"

[environment.args]

[sampling]
max_tokens = 1024

[monitor.wandb.log_extras]
interval = 10

[ckpt]