[project]
name = "zeroband"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "datasets>=3.6.0",
    "google-cloud-storage>=3.1.1", # TODO: Delete after refactor
    "loguru>=0.7.3",
    "numpy>=2.2.6",
    "pydantic>=1.10.13",
    "pydantic-settings>=2.10.1",
    "pynvml>=12.0.0",
    "tomli>=2.2.1",
    "torch>=2.7.0",
    "transformers>=4.53.0",
    "wandb>=0.20.1",
]

[project.scripts]
# TODO: Support torchrun for training
train = "zeroband.training.train:main"
orchestrator = "zeroband.training.orchestrator.orchestrator:main"
infer = "zeroband.inference.server:main"
eval = "zeroband.eval.eval:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
# Platform-specific dependencies
cu128 = ["torch>=2.7.0"]

# Entrypoint-specific dependencies
train = [
    "flash-attn>=2.8.0",
    "jaxtyping>=0.3.2",
    "beartype>=0.21.0",
    "liger-kernel>=0.5.10",
    "shardcast>=0.3.1",
]
infer = [
    "vllm>=0.9.1",
    "uvloop>=0.21.0",
]
orchestrator = [
    "openai>=1.92.2",
]
rewards = [
    "cydifflib>=1.2.0",
    "pyext",
    "pylatexenc>=2.10",
    "reasoning_gym",
]

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", extra = "cu128" }
]
pyext = { git = "git+https://github.com/justusmattern27/PyExt.git" }
reasoning_gym = { git = " git+https://github.com/open-thought/reasoning-gym.git" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "pytest>=8.4.1",
]


[tool.ruff.lint]
ignore = ["F722"] # need to ignore this for jaxtyping https://docs.kidger.site/jaxtyping/faq/

[tool.ruff]
line-length = 120