max_steps = 500
batch_size = 1024
micro_batch_size = 1
seq_len = 8192
rollouts_per_example = 8
mask_truncated_completions = false

[sampling]
temperature = 0.6
max_tokens = 8192

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

[wandb]

[environment]
id = "deepscaler-math"

[wandb.log_extras]
interval = 50

[eval]
interval = 50
environment_ids = ["math500", "aime2024", "aime2025"]
rollouts_per_example = [1, 32, 32]

[ckpt]
interval = 100