batch_size = 512
micro_batch_size = 4
rollouts_per_prompt = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-7B"

[monitor.wandb]
project = "hendrycks-math"

[environment]
id = "hendrycks-math"

[monitor.wandb.log_samples]
interval = 10
num_samples = 16

[eval]
interval = 50
benchmarks = ["math500"]