
[monitor.wandb]
project = "math-debug"

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

[optim]
lr = 1e-6

### Orchestrator ###

[orchestrator]
batch_size = 2048
micro_batch_size = 1
seq_len = 8192

[orchestrator.eval]
interval = 50
benchmarks = ["math500"]


[orchestrator.data]
name = "PrimeIntellect/INTELLECT-2-only-math"

[orchestrator.data.difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.4
max_solve_rate = 0.9

[orchestrator.sampling]
n = 16

[orchestrator.monitor.wandb.log_samples]
interval = 50
num_samples = 16

[ckpt]
