max_steps = 1000
batch_size = 2048
micro_batch_size = 1
seq_len = 8192
rollouts_per_example = 16
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"

[monitor.wandb]

[environment]
id = "intellect-math"

[environment.args]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.4
max_solve_rate = 0.9

[monitor.wandb.log_extras]
interval = 50

[eval]
interval = 50
environment_ids = ["math500", "aime2024", "aime2025"]
rollouts_per_example = [1, 16, 16]

[ckpt]