max_steps = 660
batch_size = 1024
micro_batch_size = 1
seq_len = 16384
rollouts_per_example = 16
mask_truncated_completions = false

[sampling]
temperature = 0.8

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-7B"

[monitor.wandb]

[environment]
id = "vf-skywork-math"

[environment.args]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.000001
max_solve_rate = 0.999999

[monitor.wandb.log_extras]
interval = 50

[eval]
interval = 50
environment_ids = ["vf-math500", "vf-aime2024", "vf-aime2025"]
rollouts_per_example = [1, 32, 32]

[ckpt]
interval = 200
