max_steps = 760
batch_size = 4096
micro_batch_size = 1
seq_len = 16384
rollouts_per_prompt = 16
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-32B"

[monitor.wandb]

[environment]
id = "skywork-math"

[environment.args]
solve_rate_field = "solve_rate_qwen_r1_distill_32b"
min_solve_rate = 0.000001
max_solve_rate = 0.999999

[monitor.wandb.log_extras]
interval = 50

[eval]
interval = 50
benchmarks = ["math500", "aime24", "aime25"]
rollouts_per_prompt = [1, 32, 32]

[ckpt]