## to run on H100
batch_size = 512
micro_batch_size = 2
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-7B"

[monitor.wandb]

[environment]
id = "vf-hendrycks-math"

[monitor.wandb.log_extras]
interval = 10

[eval]
interval = 50
environment_ids = ["vf-math500", "vf-aime2024", "vf-aime2025"]
rollouts_per_example = [1, 16, 16]

[ckpt]
interval = 200 